var cnItems = {
    _OTHER_: [],
    'Black Knight': '黑骑士',
    'Black Dragon': '黑龙',
    'Blue Dragon': '蓝龙',
    'Black Axe': '黑斧',
    'Brew': '酿造',
    'Bronze Arrows': '青铜箭',
    'Bronze 2H Sword': '青铜2H剑',
    'Bronze Arrowtips': '青铜箭头',
    'Bronze Bar': '青铜锭',
    'Bronze Battleaxe': '青铜战斧',
    'Bronze Boots': '青铜靴',
    'Bronze Crossbow Head': '青铜弩头',
    'Bronze Dagger': '青铜匕首',
    'Bronze Gear': '青铜装备',
    'Bronze Gloves': '青铜手套',
    'Bronze Helmet': '青铜头盔',
    'Bronze Javelin Heads': '青铜标枪头',
    'Bronze Platebody': '青铜板甲',
    'Bronze Platelegs': '青铜板腿',
    'Bronze Scimitar': '青铜弯刀',
    'Bronze Shield': '青铜盾',
    'Bronze Sword': '青铜剑',
    'Bronze Throwing Knife': '青铜飞刀',
    'Browse Combat Areas': '访问战斗区域',
    'Browse Dungeons': '访问地牢',
    'Browse Slayer Areas': '访问杀手领域',
    'Burn': '燃烧',
    'Zombie': '僵尸',
    'Zombie Hand': '僵尸之手',
    'You Have': '你拥有',
    'You have': '你拥有',
    'Wet Forest': '潮湿森林',
    'Very Easy': '很简单',
    'Very hard': '很困难',
    'Very Hard': '很困难',
    'Trees': '树',
    'Start Dungeon': '进入地牢',
    'Smith': '锻造',
    'Fish': '鱼',
    'Fisherman': '渔夫',
    'Fishing': '钓鱼',
    'Food': '食物',
    'Fletching': '造箭',
    'Fletch': '造箭',
    'Fire Cape': '火斗篷',
    'Cow': '牛',
    'Copper': '铜',
    'Combat Level': '战斗等级',
    'Combat': '战斗',
    'Combat Options': '战斗选项',
    'Combat Potions': '战斗药剂',
    'Cook': '烹饪',
    'Completion Log': '完成记录',
    'Current Axe': '当前斧子',
    'Current Fire': '当前篝火',
    'Current Rod': '当前鱼竿',
    'Current Pickaxe': '当前镐子',
    'Current Tier': '当前层',
    'Cooking': '烹饪',
    'Cooking Gloves': '烹饪手套',
    'Frozen Archer': '冰霜射手',
    'Frozen Chest': '冰霜胸甲',
    'Tin': '锡',
    'Willow Logs': '柳树原木',
    'Wizard': '巫师',
    'View Item Stats': '查看物品属性',
    'View Monster Drops': '查看怪物掉落',
    'Volcanic Cave': '火山洞穴',
    'Wet Monster': '潮湿的怪物',
    'Wizard Tower': '巫师塔',
    'Woodcutting': '伐木',
    'Unequip': '卸下',
    'Undead Graveyard': '亡灵墓地',
    'Undead Werewolf': '亡灵狼人',
    'Unique monsters and drops': '独特的怪物和掉落',
    'Unlock an extra equipment set for combat.': '解锁额外的战斗装备。',
    'Total Mining Mastery Level of 270 required to mine.': '采矿所需的总采矿精通等级为270。',
    'Test Environment': '测试环境',
    'Skill Potions': '技能药水',
    'Scroll of Aeris': '艾瑞斯卷轴',
    'Scroll of Glacia': '冰川卷轴',
    'Scroll of Ragnar': '拉格纳卷轴',
    'Scroll of Terran': '人族卷轴',
    'Seagull': '海鸥',
    'Shop': '商店',
    'Shallow Shores': '浅海岸',
    'Silver': '银',
    'Settings': '设置',
    'Seething Horned Elite': '沸腾的有角精英',
    'Smithing': '锻造',
    'Stab': '刺',
    'Status': '状态',
    'Steel': '钢',
    'Steel Bar': '钢锭',
    'Steel Dagger': '钢匕首',
    'Steel Fishing Rod': '钢钓鱼竿',
    'Steel Gear': '钢制装备',
    'Steel Knight': '钢骑士',
    'Steel Sword': '钢剑',
    'Steel Throwing Knife': '钢飞刀',
    'Stone Snake': '石蛇',
    'Strange Cave': '奇怪的洞穴',
    'Strange Eyed Monster': '奇怪的多眼怪物',
    'Strength': '力量',
    'SUBMIT IDEA': '提交想法',
    'Success Rate': '成功率',
    'Sweaty Monster': '满身是汗的怪物',
    'Angel': '天使',
    'Bank': '仓库',
    'Bars': '金属锭',
    'Black': '黑',
    'Changelog': '更新日志',
    'Chicken': '鸡',
    'Click to Activate': '点击激活',
    'Craft': '制造',
    'Crafting': '工艺',
    'Create': '创建',
    'Attack': '攻击',
    'Attack Speed': '攻击速度',
    'Attack Type': '攻击类型',
    'Attack Style': '方式',
    'Defence': '防御',
    'Eyes': '眼睛',
    'Farmer': '农民',
    'Farming': '种植',
    'Farmlands': '农田',
    'Fight': '战斗',
    'Loot All': '全部拿走',
    'Lots of Eyes': '很多眼睛',
    'Magic': '魔法',
    'Man': '人',
    'Mastery': '专精',
    'Medium': '中等',
    'Melvor Idle': '梅尔沃放置',
    'Menu': '菜单',
    'Mine': '矿山',
    'Mining': '采矿',
    'Miner': '矿工',
    'Mining Gloves': '采矿手套',
    'Mithril': '秘银',
    'Mithril Bar': '秘银锭',
    'Monsters': '怪物',
    'No potion active': '没有使用药水',
    'New Task': '新任务',
    'Fierce Devil': '凶恶魔鬼',
    'Firemaking': '生火',
    'Force Save': '强制保存',
    'Gems Gloves': '宝石手套',
    'Ghost': '幽灵',
    'Golbin': '哥布林',
    'Gloves': '手套',
    'Gold Bar': '金锭',
    'Gold': '黄金',
    'Hard': '困难',
    'Herbs': '草药',
    'Herblore': '制药',
    'Hill Giant': '山丘巨人',
    'Hitpoints': '生命值',
    'Level': '等级',
    'Light a Fire': '生火',
    'Locked': '未解锁',
    'Loading...': '加载中...',
    'Magic Chest': '魔法胸甲',
    'Magic Logs': '魔法原木',
    'Active': '活动',
    'Actions': '动作',
    'Accurate': '精准',
    'Accuracy Rating': '精准率',
    'Active Prayers': '祈祷活动',
    'Buy': '购买',
    'Coal': '煤',
    'Compost': '堆肥',
    'Cut': '砍',
    'Cooking XP Bonus': '烹饪经验值奖励',
    'Easy': '简单',
    'Cooking Skillcape': '烹饪技能斗篷',
    'Vampire': '吸血鬼',
    'Valkyrie': '瓦尔基里',
    'Yew Logs': '紫杉原木',
    '20% Faster Mining': '提升20%采矿速度',
    '4% Chance for 2x Ores': '4%的几率获得2倍矿石',
    'Adamant Axe': '精金斧',
    'Adamant Gear': '精金装备',
    'Adamant Knight': '精金骑士',
    'Adamantite': '精金',
    'Adult Farmer': '成年农民',
    'Silver Bar': '银锭',
    'Show All': '全部显示',
    'Skills': '技能',
    'Skill Upgrades': '技能升级',
    'Items': '物品',
    'Knight': '骑士',
    'Leather': '皮革',
    'Leather Armour': '皮甲',
    'Leather Boots': '皮靴',
    'Leather Gloves': '皮手套',
    'Prayer': '祈祷',
    'Potions': '药水',
    'PROGRESS': '进度',
    'Produces': '生产',
    'Progress': '进度',
    'Quick Sort Bank': '快速仓库排序',
    'Ranged': '远程',
    'Rapid': '迅速',
    'Rings': '戒指',
    'Runes': '符文',
    'Runite': '符文',
    'Reward': '奖励',
    'Rune Knight': '符文骑士',
    'Runecrafting': '符文制作',
    'Rune Gear': '符文装备',
    'Rune Essence': '符文精华',
    'Other': '其它',
    'Options': '选项',
    'Open Waters': '开阔水域',
    'Online': '在线',
    'Oak Logs': '橡木原木',
    'Master Wizard': '精灵法师',
    'Socials': '社交',
    'Teak Logs': '柚木原木',
    'Type': '类型',
    'Alpha v0.': '公测版 v0.',
    'Requires': '要求',
    'Unlocked at': '解锁于',
    'Used to Fletch Bows': '用来造羽毛弓',
    'Used to Craft Red Dragonhide Armour': '用来制作红龙皮盔甲',
    'Used to Craft Leather Armour': '用来制作皮革盔甲',
    'Used to Craft Green Dragonhide Armour': '用于制作绿龙皮盔甲',
    'Used to Craft Blue Dragonhide Armour': '用来制作蓝龙皮盔甲',
    'UNLOCKS': '解锁',
    'General Upgrades': '普通升级',
    'Shortbows': '短弓',
    'Slayer Task': '杀手任务',
    'Slayer': '杀手',
    'Slash': '砍',
    'Block': '格挡',
    'Change Equipment Set': '切换装备设置',
    'Change Password': '修改密码',
    'Current Eggs': '当前蛋',
    'View All Equipment Stats': '查看所有装备状态',
    'Water God Dungeon': '水神地牢',
    'Weird Gloop': '怪异的格洛普',
    'Thieving': '偷窃',
    'Lumberjack': '伐木工人',
    'Milestones': '里程碑',
    'Statue': '雕像',
    'Stats': '属性',
    'Statistics': '统计',
    'Statistic': '统计',
    'Spellbook': '法术书',
    'Equip the': '装备',
    'Donate': '捐赠',
    'Deep Sea Ship': '深海沉船',
    'Defence Skillcape': '防御技能斗篷',
    'Chicken Coop': '鸡舍',
    'Chance to Hit': '命中率',
    'Barren Ocean': '贫瘠海洋',
    'Max Hit': '最大伤害',
    'Max Scores': '最高分',
    'Dmg Reduction': '伤害降低',
    'Easy Mode': '简单模式',
    'Evasion': '闪避',
    'Food Efficiency': '食物效果',
    'Unlock': '解锁',
    'Longbows': '长弓',
    'Magic Skillcape': '魔术技能斗篷',
    'Maple Logs': '枫树原木',
    'Miss!': '未命中!',
    'Moss Giant': '苔藓巨人',
    'Normal': '普通',
    'Normal Logs': '普通原木',
    'Normal Mode': '普通模式',
    'Not Active': '未激活',
    'Oak Cooking Fire': '橡木烹饪火',
    'Open Easter Shop': '打开复活节商店',
    'Plant All for': '全部种植花费',
    'Plant a Seed': '播种',
    'Prayer Points': '祈祷点数',
    'Raw Blowfish': '生河豚',
    'Adamantite Bar': '精金锭',
    'Air God Dungeon': '风神殿',
    'Air Rune': '风之符文',
    'Allotments': '分配',
    'Amulet of Looting': '战利品护符',
    'An Elite CafeMedia Publisher': '精英CafeMedia出版商',
    'Arrow Shafts': '箭杆',
    'Arrows': '箭头',
    'Art of Control': '控制之技',
    'Attack  Skillcape': '攻击技能斗篷',
    'Auto Eat - Tier II': '自动进餐-II级',
    'Bandit': '强盗',
    'Bandit Base': '强盗营地',
    'Bandit Chest': '强盗宝箱',
    'Bandit Hideout': '强盗藏匿处',
    'Bandit Trainee': '强盗新兵',
    'Bank Slot': '银行槽位',
    'Bank Space Used': '银行空间',
    'Bank Value': '银行价值',
    'Barbarian Fishing': '野蛮人钓鱼',
    'Base ingredient for Potions.': '魔药的基本成分',
    'Bird Nests Potion': '燕窝药剂',
    'Blue Dragonhide': '蓝龙皮',
    'Bonfire Status': '篝火状态',
    'Bowstring': '弓弦',
    'Bypass equipment requirements for Slayer Areas': '避开杀戮地区的装备要求',
    'Capped at 2,000 SC': '最大为2000SC',
    'Castle of Kings': '国王的城堡',
    'Change Character Name': '更改角色名称',
    'Chef': '厨师',
    'Collect a random Gem for each mining action when equipped. Does not work on Rune Essence.': '装备后,每次采矿时可获得随机宝石,对符文精华无效',
    'Confetti Crossbow': '五彩弩',
    'Confused Pirate': '困惑的海盗',
    'Cooking burns no food when equipped': '装备时烹饪将不会烧焦食物',
    'Crafting Skillcape': '工艺技能斗篷',
    'Created  by Patreon (deathbyconfetti': '创建者Patreon(deathbyconfetti',
    'Created by Patreon (RS Wikis': '创建者Patreon（RS Wiki',
    'Created by Patreon (Skull': '创建者Patreon（Skull',
    'Crossbows': '弩',
    'Custom Amount': '自定义数量',
    'Cut 2 different trees simultaneously': '同时砍伐两棵不同的树',
    'Dark Horned Elite': '黑暗巨魔',
    'Dark Wizard': '黑巫师',
    'Decreased Crafting Interval': '减少制作间隔',
    'Defensive': '防御',
    'Defensive Stats': '防御值',
    'Desolate Plains': '荒原',
    'Discord': '嘈杂声',
    'Doubles the amount of items caught.': '使捕获的道具数量加倍',
    'Dragon Gear': '龙族装备',
    'Dragon Valley': '龙谷',
    'Dragonhide': '龙皮',
    'Dragonite': '龙石',
    'Dragons Den': '龙穴',
    'Drops': '掉落物',
    'Dungeon Difficulty': '地下城难度',
    'Dungeon Equipment Swapping': '地下城装备交换',
    'Earth God Dungeon': '地神殿',
    'Egg Chest': '蛋箱',
    'Elder Chest': '上古宝箱',
    'Elite': '精英',
    'Elite Chest': '精英之箱',
    'Empty': '空的',
    'Enable Equipment Swapping during dungeons.': '可在地下城中更换装备',
    'Enemy': '敌人',
    'Enemy Combat Level': '敌人战斗等级',
    'Enemy Special Attacks': '敌人特殊攻击',
    'Entry Requirements': '进入要求',
    'Equipment': '装备',
    'Equipment Sets': '装备套装 ',
    'Equipped': '装备',
    'Expanded Knowledge': '知识拓展',
    'Extra Equipment Set': '额外装备套装',
    'Fairy': '仙女',
    'Farming Skillcape': '种植技能斗篷',
    'Fight various monsters and bosses': '与不同的怪物和领主对抗',
    'Fills Farming Compost to 100% per use. +10% Increased crop harvest.': '每次使用100%填充农业堆肥。+10%的作物收成。',
    'Fire God Dungeon': '火神殿',
    'Fire Status': '火焰状态',
    'Firemaking Skillcape': '生火技能斗篷',
    'Firemaking XP Bonus when active': '激活时的生火经验奖励',
    'Fishing Skillcape': '钓鱼技能斗篷',
    'Fletching Skillcape': '弓箭技能披风',
    'Food never burns': '食物永不燃烧',
    'Forest of Goo': '粘液之森',
    'from the Spider Forest Dungeon to enable auto-looting': '从蜘蛛森林地下城中启用自动拾取',
    'Frozen Cove': '冰冻海湾',
    'Frozen Mammoth': '寒冰猛犸象',
    'Furious Horned Elite': '猖狂巨魔',
    'Gain 10%-200% of damage dealt in GP based on your current GP. Capped at 50M for 200%.': '基于你的当前金币造成10％-200％的伤害。 50M金币时达到最大值，此时伤害200%',
    'Gain 50% extra XP from Smithing when equipped': '装备后，锻造获得额外50%的经验值',
    'Game Update Available': '游戏更新可用',
    'Gem-Tipped Bolts': '宝石矢',
    'General': '常规',
    'Giant Crab': '巨蟹',
    'Giant Dungeon': '巨人地牢',
    'Golbin Village': '哥布林镇',
    'Gold Ruby Necklace': '红宝石金项链',
    'Gold Ruby Ring': '红宝石金戒指',
    'Gold Sapphire Necklace': '蓝宝石金项链',
    'Gold Sapphire Ring': '蓝宝石金戒指',
    'Gold Topaz Necklace': '黄宝石金项链',
    'Gold Topaz Ring': '黄宝石金戒指',
    'Goo Monster': '软泥怪',
    'Got a potion idea? Submit it here -->': '有魔药的主意吗？ 在这里提交->',
    'Grants access to High Lands.': '可以进入高地。',
    'Grants access to Strange Cave.': '可以进入奇异洞穴。',
    'Graveyard': '墓地',
    'Great for Slayer Training': '非常适合杀戮培训',
    'Great source of food.': '重要的食物来源。',
    'Great source of XP.': '重要的经验来源。',
    'Green Dragon': '绿龙',
    'Green Dragonhide': '绿龙皮',
    'Green Goo Monster': '绿色软泥怪',
    'Griffin': '格里芬',
    'Hall of Wizards': '巫师殿',
    'Halve Coal Requirements': '将煤炭需求减半',
    'Hard Leather Boots': '硬皮靴',
    'Hard Leather Gloves': '硬皮手套',
    'Hard Mode': '困难模式',
    'Headless Arrows': '钝头箭',
    'Headless Bolts': '钝头矢',
    'Herblore Skillcape': '制药技能斗篷',
    'High Lands': '高地',
    'High value rewards found here': '在这里可以找到高价值的奖励',
    'Highest Combat Level Monster': '最高战斗等级怪物',
    'Hitpoints Skillcape': '回复技能斗篷',
    'Holy Archer': '圣射手',
    'Holy Isles': '圣岛',
    'Ice Monster': '寒冰怪物',
    'Icy Hills': '冰山',
    'Idle': '空闲',
    'In Bank': '在银行',
    'In Development': '开发中',
    'Inacitve': '不活跃',
    'Inactive': '不活跃',
    'Inherits all Skillcape perks.': '继承所有技能斗篷特权',
    'Iron': '铁',
    'Iron 2H Sword': '铁质双手剑',
    'Iron Arrowtips': '铁质箭头',
    'Iron Bar': '铁质装备',
    'Iron Battleaxe': '铁质斧',
    'Iron Boots': '铁质靴子',
    'Iron Crossbow Head': '铁质弩头',
    'Iron Dagger': '铁质匕首',
    'Iron Gear': '铁质装备',
    'Iron Gloves': '铁质手套',
    'Iron Helmet': '铁质头盔',
    'Iron Javelin Heads': '铁质标枪头',
    'Iron Platebody': '铁质盔甲',
    'Iron Platelegs': '铁质裤子',
    'Iron Scimitar': '铁质弯刀',
    'Iron Shield': '铁质盾',
    'Iron Sword': '铁质单手剑',
    'Iron Throwing Knife': '铁质飞刀',
    'Javelins': '标枪',
    'Junior Farmer': '初级农民',
    'Junk': '垃圾',
    'just now': '就是现在',
    'Leather Body': '皮甲',
    'Leather Chaps': '皮裤',
    'Leather Cowl': '皮兜帽',
    'Leather Vambraces': '皮手套',
    'Leech': '水蛭',
    'Lemvor Pier': '梅沃尔码头',
    'Level 10 Fishing Required': '需要10级钓鱼',
    'Level 20 Woodcutting Required': '需要20级伐木',
    'Light Bonfire (10 Logs': '点燃篝火（10根原木',
    'Login': '登录',
    'Longrange': '长距离',
    'Loot to Collect': '收集战利品',
    'Magic weapon required': '需要魔法武器',
    'Magical Ring': '魔法戒指',
    'Mahogany Logs': '桃树原木',
    'Manual': '手动',
    'Many Eyed Monster': '眼魔',
    'Master Farmer': '农民主',
    'Master of Nature': '自然之主',
    'Mastery Level Up!': '熟练度等级提升！',
    'Materials': '材料',
    'Max Skillcape': '终极技能斗篷',
    'Melvor Cloud': '梅尔沃云',
    'Mind Rune': '心灵符文',
    'Mining provides x2 items per action when equipped': '装备时，每次采矿可提供x2物品',
    'Mining Skillcape': '采矿技能斗篷',
    'Mirror Shield': '镜盾',
    'Mithril 2H Sword': '秘银双手剑',
    'Mithril Arrowtips': '秘银箭头',
    'Mithril Battleaxe': '秘银斧',
    'Mithril Boots': '秘银靴子',
    'Mithril Crossbow Head': '秘银弩头',
    'Mithril Dagger': '秘银匕首',
    'Mithril Gear': '秘银装备',
    'Mithril Gloves': '秘银手套',
    'Mithril Helmet': '秘银头盔',
    'Mithril Javelin Heads': '秘银标枪头',
    'Mithril Knight': '秘银骑士',
    'Mithril Platebody': '秘银盔甲',
    'Mithril Platelegs': '秘银裤子',
    'Mithril Scimitar': '秘银弯刀',
    'Mithril Shield': '秘银盾',
    'Mithril Sword': '秘银单手剑',
    'Mithril Throwing Knife': '秘银飞刀',
    'Moist Monster': '水怪',
    'Monster Difficulty': '怪物难度',
    'Multi-Tree': '多叉树',
    'Mummy': '木乃伊',
    'Name': '名称',
    'Necklaces': '项链',
    'Normal  Cooking Fire': '普通烹饪火',
    'Normal  Logs': '普通日志',
    'Normal  Mode': '正常模式',
    'Offensive Stats': '进攻值',
    'Offline': '离线',
    'Patreon': '众筹网站',
    'Pegasus': '飞马座',
    'Penumbra': '半影',
    'Perpetual Haste': '永恒的渴望',
    'Pickpocket': '扒手',
    'Pirate Booty': '海盗藏宝',
    'Please Export your save prior to refreshing.': '请先导出您的存档，然后再刷新。',
    'Prayer Point cost reduced by': '祈祷点成本降低了',
    'Prayer Skillcape': '祷告技能斗篷',
    'Privacy Policy': '隐私政策',
    'Produce 2x items per action': '每个动作产生2倍物品',
    'Produce 2x Potions': '生产2x魔药',
    'Purple Goo Monster': '紫色软泥怪',
    'Raging Horned Elite': '狂暴巨魔',
    'Ranged Golbin': '哥布林射手',
    'Ranged Skillcape': '远程技能斗篷',
    'Raw Sardine': '沙丁鱼',
    'Raw Shrimp': '活虾',
    'Ready to harvest': '可收获',
    'Receive 1x Coal per Mining Action': '每次开采可获取1倍矿石',
    'Red Dragon': '红龙',
    'Red Dragonhide': '红龙皮',
    'Reddit': 'Reddit论坛',
    'Redwood Logs': '红杉木',
    'Register': '注册',
    'Remaining  Actions': '剩余动作',
    'Rerolling existing Slayer Tasks cost 5% of your SC': '重新刷新现有的杀戮任务会花费您SC的5％',
    'Run / Area Select': '运行/区域选择',
    'Rune Pickaxe': '符文鹤嘴锄',
    'Runecrafting Skillcape': '符文技能斗篷',
    'Sandy Shores': '桑迪海岸',
    'Scattered Goo Monster': '零散的食尸鬼怪物',
    'Secret Area': '秘密区域',
    'Shrapnel River': '弹片河',
    'Silver Ruby Necklace': '红宝石银项链',
    'Silver Ruby Ring': '红宝石银戒指',
    'Silver Sapphire Necklace': '蓝宝石银项链',
    'Silver Sapphire Ring': '蓝宝石银戒指',
    'Silver Topaz Necklace': '黄宝石银项链',
    'Silver Topaz Ring': '黄宝石银戒指',
    'Skeleton': '骷髅',
    'Skillcapes': '技能斗篷',
    'Skull Cape': '骷髅披风',
    'Slayer Cowl (Basic': '杀戮兜帽（基本',
    'Slayer Cowl (Elite': '杀戮兜帽（精致',
    'Slayer Cowl (Strong': '杀戮兜帽（强力',
    'Slayer exclusive Armour.': '杀戮专用盔甲',
    'Slayer Helmet (Basic': '杀戮头盔（基本',
    'Slayer Helmet (Elite': '杀戮头盔（精致',
    'Slayer Helmet (Strong': '杀戮头盔（强力',
    'Slayer Leather Body (Basic': '杀戮皮甲（基本',
    'Slayer Leather Body (Elite': '杀戮皮甲（精致',
    'Slayer Leather Body (Strong': '杀戮皮甲（强力',
    'Slayer Platebody (Basic': '杀戮盔甲（基本',
    'Slayer Platebody (Elite': '杀戮盔甲（精致',
    'Slayer Platebody (Strong': '杀戮盔甲（强力',
    'Slayer Skillcape': '杀戮技能斗篷',
    'Slayer Wizard Hat (Basic': '杀戮巫师帽（基本',
    'Slayer Wizard Hat (Elite': '杀戮巫师帽（精致',
    'Slayer Wizard Hat (Strong': '杀戮巫师帽（强力',
    'Slayer Wizard Robes (Basic': '杀戮巫师长袍（基本',
    'Slayer Wizard Robes (Elite': '杀戮巫师长袍（精致',
    'Slayer Wizard Robes (Strong': '杀戮巫师长袍（强力',
    'Smithing Gloves': '锻造手套',
    'Smithing Skillcape': '锻造技能斗篷',
    'Special': '特殊',
    'Special Attack Desciption': '特殊攻击说明',
    'Spider Chest': '蜘蛛箱子',
    'Spider Forest': '蜘蛛森林',
    'Standard Chest': '标准箱子',
    'Standard Combat Training': '标准战斗训练',
    'Start Fishing': '开始钓鱼',
    'Steel 2H Sword': '钢制双手剑',
    'Steel Arrowtips': '钢制箭头',
    'Steel Battleaxe': '钢制战斧',
    'Steel Boots': '钢制长靴',
    'Steel Crossbow Head': '钢制弩箭头',
    'Steel Gloves': '钢制手套',
    'Steel Helmet': '钢制头盔',
    'Steel Javelin Heads': '钢制标枪头',
    'Steel Platebody': '钢制盔甲',
    'Steel Platelegs': '钢制护腿',
    'Steel Scimitar': '钢制弯刀',
    'Steel Shield': '钢制盾牌',
    'Strength Skillcape': '力量技能斗篷',
    'Tentacle': '触手',
    'The Mastery System is in very early stages of Alpha development. It will be constantly updated and changed alongside the game.': '精通系统处于Alpha开发的早期阶段。 它将随着游戏不断更新和更改。',
    'Thieving Gloves': '盗贼手套',
    'Thieving Skillcape': '盗贼技能斗篷',
    'Toggle Auto-Reuse': '切换 自动重复',
    'Toggle Dropdown': '切换 掉落列表',
    'Toggle Skill Progress': '切换 技能进展',
    'Total Eggs': '鸡蛋总数',
    'Trench of Despair': '绝望战壕',
    'Unlimited Air, Water, Earth & Fire Runes': '无限的风，水，土和火符文',
    'Variety of monsters and drops': '各种各样的怪物和掉落物',
    'View Equipment Stats': '查看装备属性',
    'Water Rune': '水之符文',
    'Woodcutting Skillcape': '伐木技能斗篷',
    'Works with Combat & Thieving.': '与战斗和偷窃配合使用。',
    'Yep, still undefined': '是的，仍然不确定',
    'You can click and drag to rearrange bank items.': '您可以单击并拖动以重新排列银行项目。',
    //5.26
    '- A 2H Axe, Gain 50% Melee Strength Bonus when fighting a Dungeon Boss.': '- 一把双手斧，在对抗地下城Boss时获得50%近战力量加成。',
    '- A 2H weapon that always performs two consecutive attacks.': '- 一把双手武器，可以连续进行两次攻击。',
    '- A new secret Amulet. +5% chance to receive an off-item (An item from a skill that is not the main resource you are gathering). Clue to obtain': '- 一个新的神秘护身符。 +5%几率获得一件次要道具（从非你当前采集的主要资源技能中获得的道具）。待获取线索。',
    '- A Ranged Bow where its Strength Bonus and Accuracy rating scales based on the Enemy Magic Level. Special attack deals a guaranteed hit based on the Enemy Magic Level.': '- 一把根据敌人魔法等级变化力量加成和命中率的远程弓。 特殊攻击根据敌人的魔法等级附带一次必中的攻击。',
    '- Enable Equipment Swapping during dungeons.': '- 允许在地城中更换装备。',
    '- Gain 33% Ranged Strength bonus against Slayer Area or Slayer Task monsters. Upgraded from a Dragon Crossbow': '- 在杀戮区域或者对抗杀戮任务时获得33%远程力量加成。 从巨龙十字弩升级而来。',
    '- Slayer Tasks in Combat now have their own menu.': '- 战斗中的杀戮任务现在有了新的独立菜单。',
    '- This Amulet is acquired by upgrading all standard Elite Amulets, alongside the Amulet of Fury and Amulet of Torture.': '- 通过升级所有的普通精英护身符获得， 包括愤怒护身符和折磨护身符。',
    '- When equipped, you have a 20% chance to cast a magic spell for free. This cape also gives great Magic Bonuses and Damage Reduction. Purchased from the Slayer Shop.': '- 装备时你有20%几率免费释放法师。 这件斗篷还提供了大量的魔法加成和伤害减免。 在杀戮商店中购买。',
    '- When equipped, you have a 20% chance to retain all compost/gloop on a farming patch when harvesting. This means you will not have to apply any further compost to that plot.': '- 装备时你有20%几率在收获作物时保留堆肥/gloop。这意味着你不用再次对该地块施肥。',
    '. These dungeons are very dangerous, and should only be attempted by the prepared and willing. Highly Recommended stats: 85+ All Combats, and yes you will need all 3 styles to complete them all (or suffer). Do not try to complete them without sufficient Damage Reduction, you will die."': '- 这些地城非常危险， 建议完全准备好了之后再参与。 建议的属性： 85+所有战斗等级，你需要所有3种战斗方式才能完成这些地城（不然会非常难）。在没有足够高减伤时也不建议尝试，会死的很快。',
    '"The Numbers, mason, What do they mean?!"': '这些数字究竟是什么意思呢?',
    '10 All Defences': '10所有防御加成',
    '10 Melee Attack Bonus': '10近战攻击加成',
    '10 Melee Strength Bonus': '10近战力量加成',
    '10 new Fish have been introduced to the game.': '增加10种新的鱼',
    '10% grow chance per Compost': '每次合成提高10%的机会',
    '10% Thieving success rate when equipped': '装备时提升10%的偷窃成功率',
    '100% Thieving Success Rate': '100%的盗窃成功比率',
    '20% chance to preserve all runes when casting a magic spell.': '释放魔法时20%几率不消耗所有符文。',
    '20% Crop Harvest Quantity. Adding Compost is free.': '增加20%采集作物的产量。 堆肥不再有费用。',
    '20% Decreased Base Cooking, Firemaking & Smithing Interval': '降低20%烹饪、生火、锻造的基础间隔',
    '20% Decreased Base Crafting & Fletching Interval': '降低20%打造、制箭的基础间隔',
    '20% Decreased Base Herblore & Runecrafting Interval': '降低20%草药知识、符文锻造的基础间隔',
    '20% Decreased Base Mining & Woodcutting Interval': '降低20%采矿、伐木的基础间隔',
    '1) A piece from the new God Armour sets (Sets include gloves and boots).': '1）新的众神装甲套装部件（包括手套和鞋子）',
    '2) One of the new Godswords, obtainable from the respective scroll. There\'s a unique Godsword for each God.': '2）一把新的神剑，通过对应的卷轴获取。 每个神都有一把独特的神剑。',
    '4 Scrolls have been added to the game, which are acquired through defeating the Gods to receive the above items.': '增加了4个新的卷轴， 通过击败众神获得以上道具后获取。',
    '4) A Bank slot token. Claim for a free bank slot (Does not increase price of your bank slot costs': '4） 一个银行栏位代币。 领取后获得一个新的银行栏位（不增加扩展银行栏位的消耗）',
    '3) Some scrolls contain unique, powerful God Weapons such as a bow, battleaxe, staff or even a special Shield.': '3) 一些卷轴包含了新的众神武器，比如说弓、战斧、法杖以及一面特殊的盾牌',
    '4 New elemental chests have been added to the game, which can be created by upgrading 100 elemental shards received within the God Dungeons.': '增加了4个新的元素宝箱。 通过100个新的众神殿产出的元素碎片升级而成',
    '4 New God Dungeons have been added to the game - Air, Water, Earth & Fire God Dungeons': '增加了4个新的众神殿 - 风水地火',
    '4 New God Rings introduced - Deadeye, Warlock, Guardian & Fighter. These provide increased stats to various combat styles.': '增加了4个新的神戒 - 死眼，术士， 守护者，战士。他们为不同的战斗风格提供属性加成。',
    '4 New Godswords have been introduced - Aeris Godsword, Glacia Godsword, Terran Godsword, Ragnar Godsword. These are heavy hitting two-handed weapons with powerful special attacks.': '增加了4把新的神剑 - 阿瑞斯， 格兰西亚，特伦， 拉格纳。 他们是拥有强大特殊攻击，伤害很高的双手武器',
    '4 of the new Fish are able to be cooked.': '新增4种鱼食材的烹饪方式',
    '30% Faster Mining': '30% 采矿速度',
    '5% Chance for 2x Ores': '5%几率双倍矿石',
    '5% Global XP Bonus. 100% for coal per log burnt.': '5%全局经验加成。 每次燃烧木材额外获得100% 煤',
    '50% Chance to preserve Ranged Ammo per shot': '50%几率在射击时不消耗箭矢',
    '50% Chance to preserve Rune Essence': '50%几率不消耗符文精华',
    '50% Decreased Woodcutting Interval': '降低50%伐木间隔',
    '500 Charges': '500发',
    'Adamant': '精金',
    'Adamant Pickaxe': '精金镐',
    'Added 4 new special items to the game that can be acquired while Fishing.': '增加了4种可以通过钓鱼获取的特殊道具',
    'Added an option to Upgrade xAll. This can be used for various upgrade methods including Elemental Shards, rope and other things.': '增加了一个升级全部的选项。 对包括元素碎片、绳子以及许多其他事物有效。',
    'Adjusted stat values for existing longbows and shortbows': '调整了现有的长弓、短弓属性值',
    'Adjusted the Fishing Special Item weightings which increases the rarity of the main special items.': '调整了钓鱼特殊项目的权重，增加了主要特殊项目的稀有度。',
    'Adjusted the way bank popovers are handled. Hopefully this fixes the bank popovers that get stuck on the screen.': '调整了银行弹出窗口的处理方式。 希望这可以解决卡在屏幕上的银行弹出窗口。',
    '"Adjusted the wording of the "Remember Me" option within the Cloud login. It is now known as "Keep me logged in" for clarity."': '“调整了Cloud登录名中“ Remember Me”选项的措词。为了清楚起见，现在称为“ Keep me login”。',
    'Adjusted Tooltip code to hopefully fix some issues where Tooltips get stuck on the screen. Further confirmation required.': '调整了工具提示代码，以有望解决一些工具提示卡在屏幕上的问题。 需要进一步确认。',
    'Adjusted wording on some item and shop upgrades regarding speed/interval changes. Only the wording changed, the effect is still the same.': '调整了某些商品的字样，并根据速度/时间间隔的变化升级了商店。 只是措辞改变了，效果还是一样。',
    'All Ice Weapons now have the same special attack.': '所有的冰冷武器都有同样的特殊攻击了。',
    'All Javelins now require 3 logs to create, down from 5 logs.': '制造标枪所需的木材数量从5降低为3',
    'All new God Equipment requires Level 85 in their respective levels to equip.': '所有的新众神装备需要85级对应等级才能装备。',
    'All Smithing level requirements have been adjusted. This enabled mid-early late game content to be available ealier in the game. Refer to this image for all value changes': '调整了所有的锻造等级。 稍微提前了一些中期-早期终极内容。 参考以下图片',
    'Alongside this, you will now discover that some monsters have the ability to have Special Attacks. This is a new mechanic introduced to add a little more of a challenge to the Dungeon. These Specials are displayed below the monster image in combat, and the Attack Speed bar will turn yellow when they are about to use it.': '除此之外，您现在会发现某些怪物具有特殊攻击的能力。 这是引入的新机制，对地下城增加了更多挑战。 这些特殊物品显示在战斗中的怪物图像下方，并且当他们将要使用它时，攻击速度条会变为黄色。',
    'Alonside the inclusion of the God Dungeons, it was a perfect time to address an area of Combat that was lacking quite a bit -': '除了纳入地下城神之外，现在是解决尚缺很多战斗领域的绝佳时机-',
    'Although I\'m the one that developed it, pretty much all of the content and lore was planned and created by Prat. For those of you who don\'t know him - Prat generally provides a lot of assistance with balance, content ideas, number crunching and other random things around the game. He\'s my go-to person to bounce random ideas off that eventuate into content.': '尽管我是开发它的人，但是几乎所有内容和知识都是由Prat计划和创建的。 对于不认识他的人-Prat通常会为您提供平衡，内容构想，数字运算和游戏中其他随机事物的大量帮助。 他是我的理想之选，可以将随意的想法反驳为最终的内容。',
    'Amulet of Fishing now provides +20% base Fishing Speed. Changed from 5% less chance to catch junk.': '钓鱼护身符现在提供20%基础钓鱼速度， 不再减少5%获得垃圾物品的几率。',
    'Ancient Claw Special Attack now procs 5% of the time, down from 10%.': '远古爪子的特殊攻击现在有5％的时间触发，从10％降低。',
    'Ancient Dragonhide Armour': '远古龙皮甲',
    'Ancient Dragonhide Armour has been introduced. These can be found in the Dragon Den dungeon.': '引入了远古龙皮护甲。 这些可以在龙穴地牢中找到。',
    'Ancient Ring of Skills (Increased Skilling XP': '远古技能指环（增加技能经验',
    'Ancient Wizard Gear now provides +5% Damage Reduction per piece': '远古巫师系列装备每件都额外提供5%伤害减免',
    'Anglerfish': '琵琶鱼',
    'April Fools 2020 Event items have been updated to reduced GP and Healing values.': '愚人节2020事件项已更新，以降低GP和治疗值。',
    'ArChAeOloGy': '考古学',
    'Armour for each respective God has been added to the game - These sets include Helmet, Body, Legs, Gloves and Boots': '游戏中增加了每个上帝的护甲-这些装备包括头盔，身体，腿，手套和靴子',
    'Auto Eat - Tier I': '自动进食 - 1阶',
    'Auto eat activated notification': '自动进食开启提示',
    'BALANCING': '平衡中',
    'Bronze Crossbow': '青铜十字弩',
    'Bronze Javelin': '青铜标枪',
    'Carp': '鲤鱼',
    'CHANGE': '改变',
    'Easter Event': '复活节',
    'Elder Dragonhide has been introduced. Can only be acquired by defeating the Elder Dragon': '新增上古龙皮。 只有通过击败上古龙才能获得。',
    'Emerald': '绿宝石',
    'Enjoy!': '请享用！',
    'Fanfish': '方鱼',
    'Farming Skillcape now provides +20% Harvest Qty on top of the existing perk.': '现在，农耕技能斗篷可以在现有技能之上提供+ 20％的收获数量。',
    'Firemaking Mastery Tokens and the Signet Ring Half (a) should now correctly drop from offline Firemaking.': '现在，可以正确地从离线Firemaking中删除Firemastery Token和Signet Ring Half（a）。',
    'Raw Anglerfish': '生的琵琶鱼',
    'Raw Herring': '生的鲱鱼',
    'Raw Lobster': '生的龙虾',
    'Raw Magic Fish does not need to be cooked to be eaten.': '生的魔法鱼（你不需要煮熟它，它能生吃！）',
    'Raw Poison Fish': '生的毒液鱼',
    'Raw Salmon': '生的大马哈鱼',
    'Raw Seahorse': '生的海马',
    'Raw Skeleton Fish': '生的骷髅鱼',
    'Raw Swordfish': '生的剑鱼',
    'Raw Trout': '生的鳟鱼',
    'Remaining Actions': '剩余的战斗',
    'REMOVED': '已移除',
    'Ruby': '红宝石',
    'Rune Fishing Rod': '符文鱼竿',
    'Sapphire': '蓝宝石',
    'Seahorse': '海马',
    'Skeleton Fish': '骷髅鱼',
    'Preface': '前言',
    'Poison Fish': '毒液鱼',
    'Oak': '橡木',
    'only': '只有',
    'The game no longer saves during Combat. It will only save when you defeat the monster.': '游戏不再在战斗时保存。它只会在你打败怪物的时候保存。',
    'The game now saves locally when the tab/app is closed.': '现在游戏在退出时会保存到本地文件中',
    'The God Dungeons': '神之地牢',
    'There are 10 new types of fish to catch': '新增了10种新的可捕捉的鱼',
    'Topaz': '黄宝石',
    'Treasure Chest': '财宝箱',
    'use Special Attacks, so be careful!': '使用了特殊的攻击方式，因此要小心！',
    'wherearemylemons': '我的柠檬哪去了',
    'XP': '经验值',
    'You can also dig up some SUPER RARE NEVER BEFORE SEEN items that will COMPLETELY CHANGE Melvor Idle.': '你将获得一些*超级稀有之前没有*的道具，它们会*完全改变*Melvor放置的玩法',
    'You can bury Skeleton Fish for to receive 3 Prayer Points each.': '你埋葬的每条骷髅鱼，将获得3点祈祷点数',
    'Your hitpoints bar now shows a small 0.5s animation when healing from Food or Auto-Eat.': '每当你通过食物或者自动进食获得治疗时，在你的生命条上显示一个小的动画（0.5秒）',
    'Your chance to hit now shows under your max hit combat stat.': '在你的最大命中属性下方显示你的命中率',
    'You will now only receive one notification when crops are ready to harvest': '仅当有作物可以被收集时才给你显示提示。',
    'You will no longer receive a notification for degraded gloves from offline progression if you were not actually using those gloves.': '如果你没有实际使用手套时，在离线进度结算时不再会给你显示手套降级的提示。',
    'You will no longer be redirected when clicking the Melvor Coud Status text.': '当你点击Melvor云存档状态文本时，不再会重定位（跳转链接？）',
    'You will find 4 new endgame dungeons to complete. These are split up in 5 floors with increasing monster difficulty as you progress.': '新的4个究极地牢。 每个地牢分为5层，每层怪物难度提升。',
    'You now produce 4 Throwing Knives per bar, up from 2.': '每次飞刀产量由2把提升到4把',
    'You can play this Minigame while training other skills freely. You are not required to participate if you do not wish. There are no exclusive items that cannot be received outside the minigame.': '当你训练其他技能时你可以游玩迷你游戏。 这并非一个强制需求。没有只可能再迷你游戏中获得的道具。',
    'You can now craft Dragonhide Shield for the respective Hide': '你现在可以从对应的皮革中打造龙皮盾',
    'You can now lock items in the bank. Locking an item will remove the option to sell it.': '你可以从银行中锁定一件物品。被锁定的物品的售卖选项将被移除。',
    'Logout': '登出',
    'Magic Fish': '魔法鱼',
    'Information': '信息',
    'Introducing ArChAeOloGy!': '正在介绍烤咕学',
    'High Lands': '高地',
    'FIXED': '已修正',
    'Fishing has been reworked.': '钓鱼被重做了。',
    'Dragonhide Shields': '龙皮盾牌',
    'Diamond': '钻石',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
}
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
}
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
}
//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^\n(.+)Be sure to check the\n(.+)$/, '请务必检查'],
    [/^\n(.+)Cooking\n(.+)$/, '烹饪'],
    [/^\n(.+)Crafting\n(.+)$/, '制作'],
    [/^\n(.+)Farming\n(.+)$/, '种地'],
    [/^\n(.+)Firemaking\n(.+)$/, '生火'],
    [/^\n(.+)Fishing\n(.+)$/, '钓鱼'],
    [/^\n(.+)Fletching\n(.+)$/, '造箭'],
    [/^\n(.+)Herblore\n(.+)$/, '制药'],
    [/^\n(.+)Mining\n(.+)$/, '采矿'],
    [/^\n(.+)Runecrafting\n(.+)$/, '符文制作'],
    [/^\n(.+)Smithing\n(.+)$/, '锻造'],
    [/^\n(.+)Thieving\n(.+)$/, '偷窃'],
    [/^\n(.+)Woodcutting\n(.+)$/, '伐木'],
    [/^\n(.+)Attack\n(.+)$/, '攻击'],
    [/^\n(.+)Magic\n(.+)$/, '魔法'],
    [/^\n(.+)Hitpoints\n(.+)$/, '生命值'],
    [/^\n(.+)Defence\n(.+)$/, '防御'],
    [/^\n(.+)Prayer\n(.+)$/, '祈祷'],
    [/^\n(.+)Ranged\n(.+)$/, '远程'],
    [/^\n(.+)Slayer\n(.+)$/, '杀手'],
    [/^\n(.+)Strength\n(.+)$/, '力量'],
    [/^\n(.+)Select Smithing Category\n(.+)$/, '选择锻造类别'],
    [/^\n(.+)Select Herblore Category\n(.+)$/, '选择制药类别'],
    [/^\n(.+)Select Fletching Category\n(.+)$/, '选择箭羽类别'],
    [/^\n(.+)Select Crafting Category\n(.+)$/, '选择工艺分类'],
    [/^\n(.+)Select Shop Category\n(.+)$/, '选择商店分类'],
    [/^\n(.+)Select your Logs\n(.+)$/, '选择你的木头'],
    [/^\n(.+)Select your Food\n(.+)$/, '选择你的食物'],
    [/^Weird Gloop used\n(.+)$/, '怪异的格洛普使用'],
    [/^Loot to Collect (.+)$/, '收集战利品 $1'],
    [/^Logs Burnt\n(.+)$/, '烧焦的原木'],
    [/^Deaths\n(.+)$/, '死亡'],
    [/^Magic Tree\n(.+)$/, '魔法树'],
    [/^Maple Tree\n(.+)$/, '枫树'],
    [/^Mahogany Tree\n(.+)$/, '桃花心树'],
    [/^Teak Tree\n(.+)$/, '柚树'],
    [/^Yew Tree\n(.+)$/, '紫杉树'],
    [/^Normal Tree\n(.+)$/, '普通树'],
    [/^Oak Tree\n(.+)$/, '橡树'],
    [/^Materials\n(.+)$/, '物料'],
    [/^Willow Tree\n(.+)$/, '柳树'],
    [/^General Upgrades\n(.+)$/, '普通升级'],
    [/^Gloves\n(.+)$/, '手套'],
    [/^(.+) Bank Capacity$/, '$1 仓库容量'],
    [/^(.+) HP$/, '$1 生命值'],
    [/^(.+) HP Regen per interval$/, '每次恢复 $1 生命值'],
    [/^(.+) charcoal$/, '$1 木炭'],
    [/^(.+) XP \/ (.+) seconds$/, '$1 经验 \/ $2 秒'],
    [/^(.+) Quest Points$/, '$1 任务点'],
    [/^Skill Upgrades(.+)$/, '技能升级'],
    [/^Requires level (.+) mining to obtain.$/, '需要$1级采矿才能获得。'],
    [/^Wed (\d+)$/, '周三 $1'],
    [/^Thu (\d+)$/, '周四 $1'],
    [/^Fri (\d+)$/, '周五 $1'],
    [/^Sat (\d+)$/, '周六 $1'],
    [/^Sun (\d+)$/, '周日 $1'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);
var cnItem = function () {
    if (!arguments[0]) return "";
    let text = arguments[0],
        s = '';
    if (typeof (text) != "string") return text;
    else s = arguments[0].charCodeAt();
    let text_prefix = "";
    for (let prefix in cnPrefix) {
        if (text.substr(0, prefix.length) === prefix) {
            text_prefix = cnPrefix[prefix];
            text = text.substr(prefix.length)
        }
    }
    let text_postfix = "";
    for (let postfix in cnPostfix) {
        if (text.substr(-postfix.length) === postfix) {
            text_postfix = cnPostfix[postfix];
            text = text.substr(0, text.length - postfix.length)
        }
    }
    let text_reg_exclude_postfix = "";
    for (let reg of cnExcludePostfix) {
        let result = text.match(reg);
        if (result) {
            text_reg_exclude_postfix = result[0];
            text = text.substr(0, text.length - text_reg_exclude_postfix.length)
        }
    }
    if (!cnItems._OTHER_) cnItems._OTHER_ = [];
    for (let reg of cnExcludeWhole) {
        if (reg.test(text)) {
            return arguments[0]
        }
    }
    for (let [key, value] of cnRegReplace.entries()) {
        if (key.test(text)) {
            return text_prefix + text.replace(key, value) + text_reg_exclude_postfix + text_postfix
        }
    }
    for (let i in cnItems) {
        if (text == i || text == cnItems[i] && cnItems[i] != '') return text_prefix + cnItems[i] + text_reg_exclude_postfix + text_postfix
    }
    let save_cfg = 1;
    let save_text = save_cfg ? text : arguments[0]
    for (let i = 0; i < cnItems._OTHER_.length; i++) {
        if (save_text == cnItems._OTHER_[i]) return arguments[0]
    }
    if (cnItems._OTHER_.length < 500) {
        cnItems._OTHER_.push(save_text);
        cnItems._OTHER_.sort(function (a, b) {
            return a.localeCompare(b)
        })
    }
    return arguments[0]
};
transTaskMgr = {
    tasks: [],
    addTask: function (node, attr, text) {
        this.tasks.push({
            node,
            attr,
            text
        })
    },
    doTask: function () {
        let task = null;
        while (task = this.tasks.pop()) task.node[task.attr] = task.text
    },
}

function TransSubTextNode(node) {
    if (node.childNodes.length > 0) {
        for (let subnode of node.childNodes) {
            if (subnode.nodeName === "#text") {
                let text = subnode.textContent;
                let cnText = cnItem(text);
                cnText !== text && transTaskMgr.addTask(subnode, 'textContent', cnText)
            } else if (subnode.nodeName !== "SCRIPT" && subnode.nodeName !== "TEXTAREA") {
                if (!subnode.childNodes || subnode.childNodes.length == 0) {
                    let text = subnode.innerText;
                    let cnText = cnItem(text);
                    cnText !== text && transTaskMgr.addTask(subnode, 'innerText', cnText)
                } else {
                    TransSubTextNode(subnode)
                }
            } else {}
        }
    }
}! function () {
    console.log("加载汉化模块");
    let observer_config = {
        attributes: false,
        characterData: true,
        childList: true,
        subtree: true
    };
    let targetNode = document.body;
    TransSubTextNode(targetNode);
    transTaskMgr.doTask();
    let observer = new MutationObserver(function (e) {
        observer.disconnect();
        for (let mutation of e) {
            if (mutation.target.nodeName === "SCRIPT" || mutation.target.nodeName === "TEXTAREA") continue;
            if (!mutation.target.childNodes || mutation.target.childNodes.length == 0) {
                mutation.target.innerText = cnItem(mutation.target.innerText)
            } else if (mutation.target.nodeName === "#text") {
                mutation.target.textContent = cnItem(mutation.target.textContent)
            } else if (mutation.addedNodes.length > 0) {
                for (let node of mutation.addedNodes) {
                    if (node.nodeName === "#text") {
                        node.textContent = cnItem(node.textContent)
                    } else if (node.nodeName !== "SCRIPT" && node.nodeName !== "TEXTAREA") {
                        if (!node.childNodes || node.childNodes.length == 0) {
                            node.innerText = cnItem(node.innerText)
                        } else {
                            TransSubTextNode(node);
                            transTaskMgr.doTask()
                        }
                    }
                }
            }
        }
        observer.observe(targetNode, observer_config)
    });
    observer.observe(targetNode, observer_config)
}();
